#!/usr/bin/env bash
# configure my domain zone so that subdomains points to server IP
dns_msg() {
	msg_string=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $msg_string" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}


if [ "$#" == 1 ]; then
	dns_msg "$1" "www"
	dns_msg "$1" "lb-01"
	dns_msg "$1" "web-01"
	dns_msg "$1" "web-02"
elif [ "$#" == 2 ]; then
		dns_msg "$1" "$2"
fi
