#!/usr/bin/env bash
# configures nginx so it contains custom header
# shellcheck disable=SC2154
# install nginx if not exists
sudo apt update -y
sudo apt install -y nginx

SERVER_NAME=$(hostname)

# Setup default html file to be served
cat <<- EOF > /var/www/html/index.html
		<!DOCTYPE html>
		<html>
		<head>
			<title>Hello World</title>
		</head>
		<body>
			<h1>Hello World!</h2>
		</body>
		</html>
EOF

# custom 404 page
cat <<- EOF > /var/www/html/404.html
		Ceci n'est pas une page
EOF


sudo bash -c "cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80;
	add_header X-Served-By \"$SERVER_NAME\";
	server_name _;

	location / {
			root /var/www/html;
			index index.html;
	}

	location /redirect_me {
	    	return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}

	error_page 404 /404.html;
	location /404 {
		root /var/www/html;
		internal;
	}

}
EOF"

sudo service nginx restart
